modLoader="javafml" #mandatory
loaderVersion="[35,)" #mandatory (24 is current forge version)
license="MIT License"
issueTrackerURL="https://github.com/aksource/HyperDimensionalBag/issues" #optional
displayURL="https://github.com/aksource/HyperDimensionalBag/" #optional
#logoFile="examplemod.png" #optional
#credits="Thanks for this example mod goes to Java" #optional
authors="ak" #optional
[[mods]] #mandatory
modId="hyperdimensionalbag" #mandatory
version="1.16.5-1.3.2" #mandatory
displayName="HyperDimensionalBag" #mandatory
#updateJSONURL="http://myurl.me/" #optional
description='''
Add HyperDimensional Bags
'''