modLoader="javafml" #mandatory
loaderVersion="[41,)" #mandatory (24 is current forge version)
license="MIT License"
issueTrackerURL="https://github.com/aksource/HyperDimensionalBag/issues" #optional
displayURL="https://github.com/aksource/HyperDimensionalBag/" #optional
#logoFile="examplemod.png" #optional
#credits="Thanks for this example mod goes to Java" #optional
authors="ak" #optional
[[mods]] #mandatory
modId="hyperdimensionalbag" #mandatory
version="1.19-1.3.3.4" #mandatory
displayName="HyperDimensionalBag" #mandatory
updateJSONURL="https://raw.githubusercontent.com/aksource/HyperDimensionalBag/master/update.json" #optional
description='''
Add HyperDimensional Bags
'''