modLoader="javafml"
loaderVersion="[${forge_major_ver},)"
license="MIT License"
issueTrackerURL="https://github.com/aksource/HyperDimensionalBag/issues"
displayURL="https://github.com/aksource/HyperDimensionalBag/"
#logoFile="examplemod.png" #optional
#credits="Thanks for this example mod goes to Java" #optional
authors="ak"
[[mods]]
modId="hyperdimensionalbag"
version="${file.jarVersion}"
displayName="HyperDimensionalBag"
updateJSONURL="https://raw.githubusercontent.com/aksource/HyperDimensionalBag/master/update.json"
description='''
Add HyperDimensional Bags
'''